# Generated by Django 2.2.7 on 2019-12-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='index',
            field=models.CharField(max_length=3, unique=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='pid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='姓名'),
        ),
    ]
