# Generated by Django 2.2.7 on 2019-12-06 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='index',
            field=models.CharField(max_length=3, unique=True, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_todo.Priority', to_field='index'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_todo.UserInfo', to_field='user'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='姓名'),
        ),
    ]
