# Generated by Django 2.2.7 on 2019-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_auto_20191206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='0', max_length=10, null=True, verbose_name='标记'),
        ),
    ]
