# Generated by Django 2.2.7 on 2019-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_auto_20191208_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default=0, max_length=10, verbose_name='标记'),
        ),
    ]
